// Generated by Wrangler by running `wrangler types`

export interface Env {
    OAUTH_KV: KVNamespace;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    COOKIE_ENCRYPTION_KEY: string;
    ALLOWED_USERNAMES: string;
    MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
    AI: Ai;
}
